name: Deploy

on:
 push:
  branches:
   - main

jobs:
 build:
  name: Build
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repo
     uses: actions/checkout@v3

   - name: Setup Node
     uses: actions/setup-node@v3

   - name: Install dependencies
     uses: bahmutov/npm-install@v1
     with:
      working-directory: './client'
      useLockFile: 'package.json'

   - name: Build project
     run: npm run build
     working-directory: './client'
     env:
      VITE_PROD_BACK_URL: ${{ vars.VITE_PROD_BACK_URL }}
      VITE_GOOGLE_CLIENT_ID: ${{vars.VITE_GOOGLE_CLIENT_ID}}
      VITE_GOOGLE_API_KEY: ${{vars.VITE_GOOGLE_API_KEY}}
      VITE_DEEPL_API_KEY: ${{vars.VITE_DEEPL_API_KEY}}
      
   - name: Copy index.html to 404.html
     run:
      cp ./client/dist/index.html
      ./client/dist/404.html

   - name: Upload production-ready build files
     uses: actions/upload-artifact@v4
     with:
      name: production-files
      path: ./client/dist

 deploy:
  name: Deploy
  needs: build
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'

  steps:
   - name: Download artifact
     uses: actions/download-artifact@v4
     with:
      name: production-files
      path: ./client/dist

   - name: Deploy to GitHub Pages
     uses: peaceiris/actions-gh-pages@v3
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./client/dist
